# [Info]
site_name: 施海江的个人网站 # 左上角标题
site_url: https://haishangfeixiang.github.io
site_author: 施海江
site_description: 施海江的个人网站
# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/haishangfeixiang/yang-xijie.github.io # 右上角点击跳转的链接
repo_name: haishangfeixiang.github.io # 右上角的名字

## [bottom-left corner]
copyright: Copyright &copy; 2022 施海江 # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/haishangfeixiang
      name: GitHub | haishangfeixiang
# [Navigtion]
nav:
  - 讲稿:
     - about: 1/about.md
     - 1/index.md
     - sedd: 1/htthhnn.md
  - 简介:
     - pro: 2/build.md
     - git: 2/git.md
     - 2/index.md
  - 介绍:
     - myself: 3/build1.md
     - 3/index.md
